### PR TITLE
AWS-391: add --profile option

### PR DESCRIPTION
**Pull request by nathanreynolds-kcom**

### CODE REVIEW

**Comment by nathanreynolds-kcom** [comment]
@micklaing-kcom @gavinchurcher-kcom: I've demoed this to Tom, he's asked if one of you can review the code?

**Comment by micklaing** [comment]
Do we have any use cases? I can't recall needing to target a different profile whilst running cfn-sphere as the profile is only setting env vars which we can do with a myriad of other tools. If running in an AWS account (e.g. CodeBuild) then we either run in the existing context or use a cross account role - we won't (shouldn't) have any config or credentials files defined on the container

**Comment by nathanreynolds-kcom** [comment]
Maybe one for @tommitchell-kcom to answer, but the main use is running cfn-square on our laptops without requiring awsume/roleshell/etc. Less typing, and less setup for those who aren't doing it regularly (i.e outside our team)

**Comment by tommitchell-nasstar** [comment]
> Maybe one for @tommitchell-kcom to answer, but the main use is running cfn-square on our laptops without requiring awsume/roleshell/etc. Less typing, and less setup for those who aren't doing it regularly (i.e outside our team)

Exactly that, there may always be tools out there to assist with things like this, but it is preferable to not need to use them. Getting Will set up with cfn-square last week was a perfect example of this, as it took ages to get to the point where he could deploy anything.

Naturally not to be used as part of the pipeline but where we don't have pipelines available people do still run this locally and having this option available will make it easier for people who don't use it often whilst still allowing people who want to to continue using AWSume etc.

**Comment by micklaing** [comment]
> > Maybe one for @tommitchell-kcom to answer, but the main use is running cfn-square on our laptops without requiring awsume/roleshell/etc. Less typing, and less setup for those who aren't doing it regularly (i.e outside our team)
> 
> Exactly that, there may always be tools out there to assist with things like this, but it is preferable to not need to use them. Getting Will set up with cfn-square last week was a perfect example of this, as it took ages to get to the point where he could deploy anything.
> 
> Naturally not to be used as part of the pipeline but where we don't have pipelines available people do still run this locally and having this option available will make it easier for people who don't use it often whilst still allowing people who want to to continue using AWSume etc.

Thanks both - makes sense :-)

**Review by micklaing — DISMISSED** [review]
The code looks fine - can you rebase please

**Review by micklaing — APPROVED** [review]
LGTM

**Pull request merged**
