### PR TITLE
AWS-366: Retry on throttle errors

### PR DESCRIPTION
**Pull request by nathanreynolds-kcom**
cfn-square provides the `@with_boto_retry` decorator to automatically retry throttled API calls.

This only applies when Boto exceptions are wrapped in `CfnSphereBotoError` - unfortunately this isn't always the case.

Rather than track down all places that Boto exceptions may occur, we instead modify `@with_boto_retry` to also retry on unwrapped Boto exceptions.

---

**Happy to provide a demo - the reproduction steps are a little fiddly...**

### CODE REVIEW

**Comment by nathanreynolds-kcom** [comment]
Added `feature/aws-366-throttling-code-review-delete-me` to assist code review.

**Comment by nathanreynolds-kcom** [comment]
@micklaing-kcom @gavinchurcher-kcom: Another code review please, have shown to Tom that this retries upon e.g get_stack_descriptions throttling.

**Review by micklaing — COMMENTED** [review]
Not sure why we would want to retry any boto error if they aren't wrapped in a handler - unhandled exceptions should always propagate up the stack. The whole point of exception handling is to wrap only those code blocks where attempting to handle the exception is viable and required for the solution. 

Are we trying to overcome an issue in our deployment process by adding this implementation which seems to be by passing standard exception handling

**Comment by nathanreynolds-kcom** [comment]
> Not sure why we would want to retry any boto error if they aren't wrapped in a handler - unhandled exceptions should always propagate up the stack. The whole point of exception handling is to wrap only those code blocks where attempting to handle the exception is viable and required for the solution.

We're not retrying all errors. Functions have to opt-in via the `@with_boto_retry` decorator, and the failing AWS calls must have Code==Throttling. That's the original cfn-sphere design so no changes from that perspective.

For this to work, boto exceptions must be wrapped in a `CfnSphereBotoError` before `@with_boto_retry` recognises a retryable event. Unfortunately the code isn't diligent about doing so. For example, get_stacks is retried but get_stack_descriptions isn't.

IMO that's a design failure. This PR removes the requirement to wrap exceptions but still retries throttling errors.

**Review by micklaing — APPROVED** [review]
LGTM

**Pull request merged**
