### PR TITLE
Added https download functionality allowing use of AWS supplied templates

### PR DESCRIPTION
**Pull request by micklaing**

### CODE REVIEW

**Review by steveparker-1984 — CHANGES_REQUESTED** [review]
bs4 needs to be marked as a dependency so the unit tests can run (and for deployment). Looks like these go in build.py

You'll need to increment line 22 version number also in order for the change to be deployed to pypi

Otherwise it looks ok

**Comment by micklaing** [comment]
Added dependencies and bumped up the version number

**Comment by steveparker-1984** [comment]
@micklaing-kcom I added a commit to remove the urllib.request dependency. It's a native package and it caused the build to fail. If you pull my commit, then squash and retest, I'll merge.

**Comment by micklaing** [comment]
Squashed and re-tested.

**Review by steveparker-1984 — APPROVED** [review]
LGTM

**Pull request merged**
