### PR TITLE
Change set update

### PR DESCRIPTION
**Pull request by rayoogmy**
Added code to:
 - create change set for a new stack
 - delete failed change set

### CODE REVIEW

**Review by steveparker-1984 — CHANGES_REQUESTED** [review]
You'll want to update the pip version number so the change deploys on merge.

**Comment by rayoogmy** [comment]
@steveparker-kcom where do I do that?

**Comment by steveparker-1984** [comment]
@rayhwang-kcom build.py line 22

**Comment by rayoogmy** [comment]
Updated to 1.40

**Review by steveparker-1984 — APPROVED** [review]

**Comment by steveparker-1984** [comment]
LGTM - Squash please @rayhwang-kcom

**Comment by rayoogmy** [comment]
Squashed

**Pull request merged**
